#!/bin/bash
# ============================================================================
# audit-config.sh - Audit all 6 configuration dimensions in 1 JSON call
# Usage: audit-config.sh
# Exit 0 = always (fail-open)
#
# Replaces 15 sequential checks in /audit
# ============================================================================

set +e  # Fail-open

# Require jq for JSON output
if ! command -v jq &>/dev/null; then
    echo '{"error":"jq not installed"}' >&2
    exit 0
fi

CLAUDE_DIR="$HOME/.claude"
PROJECT_DIR="${CLAUDE_PROJECT_DIR:-/workspace}"

# --- Agents ---
AGENT_COUNT=$(find "$CLAUDE_DIR/agents" -name "*.md" -type f 2>/dev/null | wc -l | tr -d ' ')
REGISTRY_EXISTS=false
[ -f "$CLAUDE_DIR/agents/registry.json" ] && REGISTRY_EXISTS=true

# --- Hooks (scripts) ---
HOOK_COUNT=$(find "$CLAUDE_DIR/scripts" -name "*.sh" -type f 2>/dev/null | wc -l | tr -d ' ')

# Count event types from settings.json
EVENT_TYPES=0
if [ -f "$CLAUDE_DIR/settings.json" ] && command -v jq &>/dev/null; then
    EVENT_TYPES=$(jq '.hooks | keys | length' "$CLAUDE_DIR/settings.json" 2>/dev/null || echo "0")
fi

# --- MCP ---
MCP_SERVERS=0
MCP_FRAGMENTS=0
if [ -f "$HOME/.claude.json" ] && command -v jq &>/dev/null; then
    MCP_SERVERS=$(jq '.mcpServers | length' "$HOME/.claude.json" 2>/dev/null || echo "0")
fi
MCP_FRAGMENTS=$(find /etc/mcp/fragments /etc/mcp/features -name "*.json" -type f 2>/dev/null | wc -l | tr -d ' ')

# --- Settings ---
VERSION_MATCH=true
if [ -f "$PROJECT_DIR/.devcontainer/images/.claude/settings.json" ] && [ -f "$CLAUDE_DIR/settings.json" ]; then
    BUILT=$(md5sum "$PROJECT_DIR/.devcontainer/images/.claude/settings.json" 2>/dev/null | cut -d' ' -f1 || echo "a")
    RUNTIME=$(md5sum "$CLAUDE_DIR/settings.json" 2>/dev/null | cut -d' ' -f1 || echo "b")
    [ "$BUILT" != "$RUNTIME" ] && VERSION_MATCH=false
fi

# --- Security ---
AI_COMMITS=$(git -C "$PROJECT_DIR" log --oneline -20 2>/dev/null | grep -ciE 'co-authored-by.*claude|generated by ai' 2>/dev/null || echo 0)
AI_COMMITS=$(echo "$AI_COMMITS" | tr -d '[:space:]')

# --- Documentation ---
CLAUDE_MD_COUNT=$(find "$PROJECT_DIR" -name "CLAUDE.md" -not -path "*/node_modules/*" -not -path "*/.git/*" 2>/dev/null | wc -l | tr -d ' ')
OVERSIZED="[]"
while IFS= read -r f; do
    [ -z "$f" ] && continue
    lines=$(wc -l < "$f" 2>/dev/null | tr -d ' ')
    if [ "$lines" -gt 200 ] 2>/dev/null; then
        OVERSIZED=$(echo "$OVERSIZED" | jq --arg f "$f" --arg l "$lines" '. + [{"file": $f, "lines": ($l | tonumber)}]')
    fi
done < <(find "$PROJECT_DIR" -name "CLAUDE.md" -not -path "*/node_modules/*" -not -path "*/.git/*" 2>/dev/null)

PATTERNS_COUNT=$(find "$CLAUDE_DIR/docs" -name "*.md" -type f 2>/dev/null | wc -l | tr -d ' ')

# --- Commands ---
COMMAND_COUNT=$(find "$CLAUDE_DIR/commands" -maxdepth 1 -name "*.md" -type f 2>/dev/null | wc -l | tr -d ' ')

# --- Output JSON ---
jq -n \
    --arg agent_count "$AGENT_COUNT" \
    --argjson registry "$REGISTRY_EXISTS" \
    --arg hook_count "$HOOK_COUNT" \
    --arg event_types "$EVENT_TYPES" \
    --arg mcp_servers "$MCP_SERVERS" \
    --arg mcp_fragments "$MCP_FRAGMENTS" \
    --argjson version_match "$VERSION_MATCH" \
    --arg ai_commits "$AI_COMMITS" \
    --arg claude_md_count "$CLAUDE_MD_COUNT" \
    --argjson oversized "$OVERSIZED" \
    --arg patterns_count "$PATTERNS_COUNT" \
    --arg command_count "$COMMAND_COUNT" \
    '{
        agents: {count: ($agent_count | tonumber), registry_exists: $registry},
        hooks: {count: ($hook_count | tonumber), event_types: ($event_types | tonumber)},
        mcp: {servers: ($mcp_servers | tonumber), fragments: ($mcp_fragments | tonumber)},
        settings: {version_match: $version_match},
        security: {ai_commits_found: ($ai_commits | tonumber)},
        docs: {claude_md_count: ($claude_md_count | tonumber), oversized: $oversized, patterns_count: ($patterns_count | tonumber)},
        commands: {count: ($command_count | tonumber)}
    }'
