#!/bin/bash
# shellcheck disable=SC2011  # ~/.claude/commands/*.md is controlled, no whitespace filenames
# ============================================================================
# post-compact.sh - Restore critical context after context compaction
# SessionStart hook for "compact" matcher
# Exit 0 = success, outputs additionalContext to inject into Claude's context
# ============================================================================

set -euo pipefail

# Read hook input (best-effort, resilient to empty/malformed input)
INPUT="$(cat || true)"

# Parse source field (graceful if jq unavailable or input malformed)
SOURCE=""
if command -v jq >/dev/null 2>&1; then
    SOURCE="$(printf '%s' "$INPUT" | jq -r '.source // ""' 2>/dev/null || true)"
fi

# Only act on compact events
if [[ "$SOURCE" != "compact" ]]; then
    exit 0
fi

# Build available skills list dynamically
SKILLS_LIST=""
COMMANDS_DIR="$HOME/.claude/commands"
if [[ -d "$COMMANDS_DIR" ]]; then
    SKILLS_LIST=$(ls -1 "$COMMANDS_DIR"/*.md 2>/dev/null | xargs -I{} basename {} .md | tr '\n' ', ' | sed 's/,$//')
fi

# JSON-escape the skills list to prevent heredoc/JSON breakage
SKILLS_ESCAPED="${SKILLS_LIST:-git, review, search, plan, do, test, init, update}"
if command -v jq >/dev/null 2>&1; then
    SKILLS_ESCAPED=$(printf '%s' "$SKILLS_ESCAPED" | jq -Rs '.' | sed 's/^"//;s/"$//')
else
    # Manual JSON escaping fallback: backslash, double-quote, newline
    SKILLS_ESCAPED="${SKILLS_ESCAPED//\\/\\\\}"
    SKILLS_ESCAPED="${SKILLS_ESCAPED//\"/\\\"}"
fi

# Output critical reminders as additionalContext
# This gets injected into Claude's context after compaction
cat << EOF
{
  "hookSpecificOutput": {
    "hookEventName": "SessionStart",
    "additionalContext": "## POST-COMPACTION CRITICAL RULES\n\n### 1. MCP-FIRST RULE (MANDATORY)\nALWAYS use MCP tools BEFORE CLI binaries:\n- GitHub: mcp__github__* (not gh CLI)\n- Browser: mcp__playwright__* (not npx playwright)\n- Docs: mcp__context7__* (for library docs)\n\n### 2. RTK-FIRST (MANDATORY)\nRTK PreToolUse hook auto-rewrites Bash commands for 60-90% token savings.\n'rtk gain' = analytics, 'rtk discover' = find missed opportunities.\nNo semantic-embedding tooling — use targeted Grep + Read in agents.\n\n### 3. ENVIRONMENT AWARENESS\nALWAYS check environment variables and .env files:\n- Run: env | grep -E 'TOKEN|KEY|SECRET' (masked)\n- Check: /workspace/.env, .devcontainer/.env\n- MCP tokens are pre-configured in mcp.json\n- NEVER ask user for tokens if MCP is available\n\n### 4. NO AI MENTIONS IN COMMITS\nNEVER include in commit messages:\n- Co-Authored-By with Claude/Anthropic/AI/GPT\n- Generated by/with AI references\n- Robot emoji or AI tool names\nHook commit-validate.sh enforces this automatically.\n\n### 5. AVAILABLE SKILLS\nUse Skill tool to invoke: ${SKILLS_ESCAPED}\n- /git --commit: Create branch + commit + PR\n- /review: AI-powered code review\n- /search: Documentation research\n- /plan: Planning mode\n- /do: Iterative task execution\n\n### 6. CONTEXT HIERARCHY\nRead CLAUDE.md files for full context:\n- /workspace/CLAUDE.md (project rules)\n- .devcontainer/CLAUDE.md (container config)\n- .devcontainer/images/CLAUDE.md (image details)\n- .devcontainer/features/*/CLAUDE.md (language rules)\nUpdate relevant CLAUDE.md when modifying code structure.\n\n### 7. GIT WORKFLOW\nNEVER commit directly to main/master.\nALWAYS use /git skill which creates branch + PR.\n\n### 8. SAFEGUARDS\nNEVER delete without explicit approval:\n- Files in .claude/ directory\n- Files in .devcontainer/ directory\n\n### 9. CONTEXT RECOVERY (POST-COMPACTION)\nAfter compaction, check for persisted state:\n- Plans: Glob .claude/plans/*.md (read most recent for current task)\n- Contexts: Glob .claude/contexts/*.md (research from /search)\n- Review fixes: .claude/plans/review-fixes-*.md (from /review)\nThese files survive compaction and contain valuable context.\nIf working on a task, read the relevant plan/context files to restore state.\n\n**Context was compacted. Verify current task state before continuing.**"
  }
}
EOF

exit 0
