#!/bin/bash
# shellcheck disable=SC1090,SC1091
# ============================================================================
# sync-features.sh - 3-way safe sync for .devcontainer/features/
# ============================================================================
# Sourced by postStart.sh (step_sync_features) and by /update apply.md
# to mirror the template's features/ tree into a consumer repo without
# clobbering consumer-modified files.
#
# Phase 1 (this file): per-file git-dirty + byte-identical guard.
# Phase 2 (manifest):  hash manifest 3-way merge — see _sync_via_manifest stub.
#
# See plan: .claude/plans/2026-04-28-fix-poststart-features-sync-overwrite.md
# Tracking issue: kodflow/devcontainer-template#334
# ============================================================================

# Counter exported so callers can report skips after the loop.
export FEATURES_SYNC_SKIPPED=0

# Path to the shipped-content hash manifest. Generated by CI in
# .github/workflows/docker-images.yml via .devcontainer/scripts/build-
# features-manifest.py and embedded into the image at build time.
# Empty / missing → manifest mode disabled, callers fall back to Phase 1
# behaviour (git-dirty guard only).
: "${FEATURES_MANIFEST:=/etc/devcontainer-template/.template-files.json}"

# Manifest-aware 3-way merge for a single file.
# Args: $1 = src absolute path, $2 = dst absolute path, $3 = relative path
# Return codes (mirror _sync_file_safely):
#   0 = copied  (manifest proves consumer untouched → safe overwrite)
#   1 = undecided (manifest missing / tools missing → caller falls through)
#   2 = preserved (manifest detected consumer-modified content → skipped)
_sync_via_manifest() {
    local src="$1" dst="$2" rel="$3"
    [ -f "$FEATURES_MANIFEST" ] || return 1
    command -v jq >/dev/null 2>&1 || return 1
    command -v sha256sum >/dev/null 2>&1 || return 1

    local prev_hash
    prev_hash=$(jq -r --arg r "$rel" '.files[$r] // empty' "$FEATURES_MANIFEST" 2>/dev/null)
    if [ -z "$prev_hash" ]; then
        # New upstream path; consumer happens to have unrelated content at
        # the same location. Safer to preserve than to overwrite blindly.
        log_warning "Skipping features/${rel}: new upstream path collides with consumer file"
        return 2
    fi

    local dst_hash
    dst_hash="sha256:$(sha256sum "$dst" 2>/dev/null | awk '{print $1}')"
    if [ "$dst_hash" = "$prev_hash" ]; then
        # Consumer untouched since last image — safe overwrite.
        cp -a "$src" "$dst"
        return 0
    fi

    log_warning "Skipping features/${rel}: consumer-modified content (sha256 differs from last shipped)"
    return 2
}

# Manifest-aware deletion for files removed upstream. Iterates the previous
# manifest, removing dst files that (a) were shipped before, (b) are no
# longer shipped, and (c) consumer hasn't touched. Counts toward the
# preserved tally when the consumer modified a now-removed file.
# Args: $1 = src absolute path, $2 = dst absolute path
_sync_apply_deletions() {
    local src="$1" dst="$2"
    [ -f "$FEATURES_MANIFEST" ] || return 0
    command -v jq >/dev/null 2>&1 || return 0
    command -v sha256sum >/dev/null 2>&1 || return 0

    local rel src_path dst_path prev_hash dst_hash
    while IFS= read -r rel; do
        [ -n "$rel" ] || continue
        src_path="$src/$rel"
        dst_path="$dst/$rel"
        [ -e "$src_path" ] && continue            # still shipped upstream
        [ -e "$dst_path" ] || continue            # already gone
        prev_hash=$(jq -r --arg r "$rel" '.files[$r] // empty' "$FEATURES_MANIFEST" 2>/dev/null)
        [ -n "$prev_hash" ] || continue
        dst_hash="sha256:$(sha256sum "$dst_path" 2>/dev/null | awk '{print $1}')"
        if [ "$dst_hash" = "$prev_hash" ]; then
            rm -f "$dst_path"
            FEATURES_SYNC_DELETED=$((FEATURES_SYNC_DELETED + 1))
        else
            log_warning "Keeping features/${rel}: removed upstream but consumer modified"
            FEATURES_SYNC_SKIPPED=$((FEATURES_SYNC_SKIPPED + 1))
        fi
    done < <(jq -r '.files | keys[]' "$FEATURES_MANIFEST" 2>/dev/null)
    return 0
}

# 3-way file copy with consumer-edit protection.
# Args: $1 = src absolute path, $2 = dst absolute path, $3 = workspace root
# Return codes (caller drives counters; never fatal):
#   0 = wrote (new file or safe overwrite)
#   1 = noop (byte-identical, no I/O)
#   2 = preserved (consumer-modified, skipped on purpose)
_sync_file_safely() {
    local src="$1"
    local dst="$2"
    local ws="$3"
    local rel="${dst#"${ws}"/.devcontainer/features/}"

    # Case 1: dst missing → copy (new file from upstream).
    if [ ! -e "$dst" ]; then
        mkdir -p "$(dirname "$dst")"
        cp -a "$src" "$dst"
        return 0
    fi

    # Case 2: byte-identical → noop.
    if cmp -s "$src" "$dst"; then
        return 1
    fi

    # Case 3: tracked + dirty in consumer git → preserve consumer WIP.
    # Without git, we cannot tell WIP from a committed divergence; the
    # manifest path (Phase 2) closes that gap. Until then, fall through.
    if [ -d "$ws/.git" ] && command -v git >/dev/null 2>&1; then
        if git -C "$ws" ls-files --error-unmatch -- ".devcontainer/features/${rel}" >/dev/null 2>&1; then
            if ! git -C "$ws" diff --quiet --exit-code -- ".devcontainer/features/${rel}" >/dev/null 2>&1; then
                log_warning "Skipping features/${rel}: consumer has uncommitted changes (commit or run /update first)"
                return 2
            fi
        fi
    fi

    # Case 4: manifest-aware decision. Propagates the manifest's verdict
    # (0 = copied, 2 = preserved). Only return 1 (undecided) falls through.
    _sync_via_manifest "$src" "$dst" "$rel"
    local rc=$?
    case "$rc" in
        0|2) return $rc ;;
    esac

    # Case 5: fallback — overwrite. Reached only when no manifest is
    # available; Phase 2 narrows this case to absent-tooling environments.
    cp -a "$src" "$dst"
    return 0
}

# Per-file walk over the embedded features tree. Replaces the previous
# `rsync -a --delete --checksum` call. `--delete` is intentionally dropped
# in Phase 1 (no manifest yet → cannot tell consumer-added from upstream-
# removed files). Phase 2 restores deletion via the hash manifest.
sync_features_tree() {
    local src="$1"
    local dst="$2"
    local ws="$3"

    if [ ! -d "$src" ]; then
        log_warning "sync_features_tree: source dir missing ($src)"
        return 1
    fi
    mkdir -p "$dst"

    FEATURES_SYNC_SKIPPED=0
    FEATURES_SYNC_DELETED=0
    local copied=0 noop=0
    local rc
    while IFS= read -r -d '' src_file; do
        local rel="${src_file#"$src"/}"
        local dst_file="$dst/$rel"
        _sync_file_safely "$src_file" "$dst_file" "$ws"
        rc=$?
        case "$rc" in
            0) copied=$((copied + 1)) ;;
            1) noop=$((noop + 1)) ;;
            2) FEATURES_SYNC_SKIPPED=$((FEATURES_SYNC_SKIPPED + 1)) ;;
        esac
    done < <(find "$src" -type f -print0)

    # Manifest-aware deletion. Safe to call when the manifest is missing —
    # the helper short-circuits and leaves consumer-added files alone.
    _sync_apply_deletions "$src" "$dst"

    log_success ".devcontainer/features/ synced ($copied copied, $noop unchanged, $FEATURES_SYNC_DELETED removed, $FEATURES_SYNC_SKIPPED preserved)"
    if [ "$FEATURES_SYNC_SKIPPED" -gt 0 ]; then
        log_info "Tip: \`git status -- .devcontainer/features/\` shows preserved consumer edits"
    fi
    return 0
}
